---
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint

default_install_hook_types: [pre-commit, prepare-commit-msg]
ci:
  autofix_commit_msg: "chore: Auto fix by pre-commit hooks [skip changelog]"
  autofix_prs: true
  autoupdate_commit_msg: "chore: Auto update by pre-commit hooks [skip changelog]"
